---
booktitle: Proceedings of the 19th International Conference on Artificial Intelligence
  and Statistics
volume: 51
year: '2016'
start: 2016-05-09
end: 2016-05-11
published: 2016-05-02
shortname: AISTATS
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: AISTATS-2016
month: 0
cycles: false
editor:
- given: Arthur
  family: Gretton
- given: Christian C.
  family: Robert
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 19th International Conference on Artificial Intelligence and Statistics
    Held in Cadiz, Spain on 09-11 May 2016

  Published as Volume 51 by the Proceedings of Machine Learning Research on 02 May 2016.

  Volume Edited by:
    Arthur Gretton
    Christian C. Robert

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: '09--11 May'
url: http://proceedings.mlr.press
baseurl: "/v51"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v51
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Artificial Intelligence and Statistics
  url: http://www.aistats.org/aistats2016/
  location: Cadiz, Spain
  dates:
  - 2016-05-09
  - 2016-05-10
  - 2016-05-11
  number: 19
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
